export const ERROR_MESSAGES = {
  NO_PACKAGE_JSON: 'NO_PACKAGE_JSON',
  CANNOT_DETECT_PACKAGE_MANAGER: 'CANNOT_DETECT_PACKAGE_MANAGER',
};

export const CONSOLE_GREEN = '\u001b[32m';
export const CONSOLE_RESET = '\u001b[0m';
